### ISSUE TITLE
Statistics: how can we test the Ha?

### ISSUE THREAD

**Issue by AntonioAlaia** [DataAccess2020/class-exercise1#1]
We have 10 levels of income and their vote proportion (where 0 is NO and 1 is YES); how can we test the Ha: there's a relationship between levels of income and vote behaviour ?

**Comment by AntonioAlaia** [comment]
Edit: I'm doing a contingency table with Chi^2 test, do you know any package that can help me do it easily?

**Comment by maria-ascolese** [comment]
You can use the [gmodels package]( https://cran.r-project.org/web/packages/gmodels/gmodels.pdf)

**Comment by AntonioAlaia** [comment]
Thanks, I'm using it in 33faba578958bf76e82b1362b691b10133671509 , check it out!
