### ISSUE TITLE
We need to add literature to the Rmd

### ISSUE THREAD

**Issue by maria-ascolese** [DataAccess2020/class-exercise1#2]

**Comment by AntonioAlaia** [comment]
Check this study: [DiMaria, S. (2018). Towards a Unified Italy. Historical, Cultural, and Literary Perspectives on the
 Southern Question, Italian and Italian American Studies, Palgrave Macmillan, pp. 85-109 ](https://link.springer.com/book/10.1007/978-3-319-90766-6)

**Comment by maria-ascolese** [comment]
Thanks, I've used it in the markdown, check: 65a2d103c07cc7a0b40c48dd8e378482714cf24e
